"""String enums used across the MarketPilot runtime."""

from enum import StrEnum


class RunStatus(StrEnum):
    """Lifecycle of a complete research run."""

    CREATED = "CREATED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class TaskStatus(StrEnum):
    """Explicit lifecycle of a task node."""

    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    BLOCKED = "BLOCKED"
    CANCELLED = "CANCELLED"


class TaskType(StrEnum):
    """Domain-level task categories."""

    MARKET_RESEARCH = "MARKET_RESEARCH"
    PRODUCT_DISCOVERY = "PRODUCT_DISCOVERY"
    REVIEW_RESEARCH = "REVIEW_RESEARCH"
    COMPETITOR_RESEARCH = "COMPETITOR_RESEARCH"
    CANDIDATE_AGGREGATION = "CANDIDATE_AGGREGATION"
    RISK_ANALYSIS = "RISK_ANALYSIS"
    DECISION = "DECISION"
    EVIDENCE_VERIFICATION = "EVIDENCE_VERIFICATION"


class AgentRole(StrEnum):
    """Roles with distinct responsibilities, not chat personas."""

    RESEARCH_MANAGER = "RESEARCH_MANAGER"
    MARKET_RESEARCH = "MARKET_RESEARCH"
    PRODUCT_RESEARCH = "PRODUCT_RESEARCH"
    REVIEW_MINING = "REVIEW_MINING"
    COMPETITOR_RESEARCH = "COMPETITOR_RESEARCH"
    RISK_ANALYSIS = "RISK_ANALYSIS"
    DECISION = "DECISION"
    EVIDENCE_VERIFIER = "EVIDENCE_VERIFIER"


class AgentStatus(StrEnum):
    """Result status returned by an agent."""

    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class ToolResultStatus(StrEnum):
    """Structured outcome categories for tool calls."""

    SUCCESS = "SUCCESS"
    RETRYABLE_ERROR = "RETRYABLE_ERROR"
    PERMANENT_ERROR = "PERMANENT_ERROR"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    RATE_LIMITED = "RATE_LIMITED"
    TIMEOUT = "TIMEOUT"
    INVALID_INPUT = "INVALID_INPUT"
    REPLAY_MISS = "REPLAY_MISS"
    BUDGET_EXHAUSTED = "BUDGET_EXHAUSTED"


class EvidenceSourceType(StrEnum):
    """Provider-neutral source categories."""

    MOCK = "MOCK"
    WEB_PAGE = "WEB_PAGE"
    SEARCH_RESULT = "SEARCH_RESULT"
    PRODUCT_CATALOG = "PRODUCT_CATALOG"
    REVIEW_FEED = "REVIEW_FEED"
    MARKET_SIGNAL = "MARKET_SIGNAL"
    MEMORY = "MEMORY"


class Decision(StrEnum):
    """Business decision attached to a recommendation."""

    STRONG_GO = "STRONG_GO"
    GO = "GO"
    WATCH = "WATCH"
    NO_GO = "NO_GO"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"


class MemoryScope(StrEnum):
    """Conceptual memory partitions."""

    WORKING = "WORKING"
    EPISODIC = "EPISODIC"
    SEMANTIC = "SEMANTIC"
    SKILL = "SKILL"


class EventType(StrEnum):
    """Machine-readable trajectory event types."""

    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    RUN_FAILED = "RUN_FAILED"
    TASK_CREATED = "TASK_CREATED"
    TASK_READY = "TASK_READY"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    TASK_RETRIED = "TASK_RETRIED"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    TOOL_CALLED = "TOOL_CALLED"
    TOOL_SUCCEEDED = "TOOL_SUCCEEDED"
    TOOL_FAILED = "TOOL_FAILED"
    EVIDENCE_CREATED = "EVIDENCE_CREATED"
    FINDING_CREATED = "FINDING_CREATED"
    STATE_UPDATED = "STATE_UPDATED"
    MEMORY_READ = "MEMORY_READ"
    MEMORY_WRITTEN = "MEMORY_WRITTEN"
    RECOMMENDATION_CREATED = "RECOMMENDATION_CREATED"
    EVALUATION_COMPLETED = "EVALUATION_COMPLETED"
    PROMPT_RENDERED = "PROMPT_RENDERED"
    LLM_REQUESTED = "LLM_REQUESTED"
    LLM_COMPLETED = "LLM_COMPLETED"
    LLM_FAILED = "LLM_FAILED"
    LLM_RETRIED = "LLM_RETRIED"
    STRUCTURED_OUTPUT_VALIDATED = "STRUCTURED_OUTPUT_VALIDATED"
    STRUCTURED_OUTPUT_REJECTED = "STRUCTURED_OUTPUT_REJECTED"
    TOOL_REQUESTED_BY_MODEL = "TOOL_REQUESTED_BY_MODEL"
    SEARCH_REQUESTED = "SEARCH_REQUESTED"
    SEARCH_COMPLETED = "SEARCH_COMPLETED"
    SEARCH_FAILED = "SEARCH_FAILED"
    SOURCE_DISCOVERED = "SOURCE_DISCOVERED"
    SOURCE_RETRIEVAL_STARTED = "SOURCE_RETRIEVAL_STARTED"
    SOURCE_RETRIEVAL_COMPLETED = "SOURCE_RETRIEVAL_COMPLETED"
    SOURCE_RETRIEVAL_FAILED = "SOURCE_RETRIEVAL_FAILED"
    SOURCE_SNAPSHOT_CREATED = "SOURCE_SNAPSHOT_CREATED"
    SOURCE_DEDUPLICATED = "SOURCE_DEDUPLICATED"
    REPLAY_HIT = "REPLAY_HIT"
    REPLAY_MISS = "REPLAY_MISS"
    RESEARCH_BUDGET_UPDATED = "RESEARCH_BUDGET_UPDATED"
    RESEARCH_BUDGET_EXHAUSTED = "RESEARCH_BUDGET_EXHAUSTED"


class EvidenceKind(StrEnum):
    """Distinguishes external observations from LLM-generated interpretations."""

    OBSERVATION = "OBSERVATION"
    INFERENCE = "INFERENCE"
    SYNTHESIS = "SYNTHESIS"
