"""initial schema

Revision ID: f3c4ed1987f9
Revises:
Create Date: 2026-08-28 13:22:39.607665
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f3c4ed1987f9"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmark_suites",
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("manifest", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("suite_id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("git_commit", sa.String(length=64), nullable=False),
        sa.Column("dataset", sa.String(length=200), nullable=False),
        sa.Column("dataset_version", sa.String(length=50), nullable=False),
        sa.Column("generator_version", sa.String(length=50), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("benchmark_suite", sa.String(length=200), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("prompt_versions", sa.JSON(), nullable=False),
        sa.Column("research_budget", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("experiment_id"),
    )
    op.create_table(
        "research_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("market", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("objective", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("budget", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("run_id"),
    )
    op.create_index(
        "ix_research_runs_market_category", "research_runs", ["market", "category"], unique=False
    )
    op.create_index(op.f("ix_research_runs_status"), "research_runs", ["status"], unique=False)
    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("uri", sa.String(length=2048), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source_id"),
        sa.UniqueConstraint("source_type", "uri", name="uq_source_type_uri"),
    )
    op.create_index(op.f("ix_sources_source_type"), "sources", ["source_type"], unique=False)
    op.create_table(
        "benchmark_tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("task_key", sa.String(length=200), nullable=False),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("market", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("environment_id", sa.String(length=200), nullable=False),
        sa.Column("allowed_budget", sa.JSON(), nullable=False),
        sa.Column("rubric", sa.JSON(), nullable=False),
        sa.Column("hidden_ground_truth_ref", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["suite_id"], ["benchmark_suites.suite_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
        sa.UniqueConstraint("suite_id", "task_key", name="uq_benchmark_task_key"),
    )
    op.create_index(
        op.f("ix_benchmark_tasks_suite_id"), "benchmark_tasks", ["suite_id"], unique=False
    )
    op.create_table(
        "evaluations",
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("checks", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("evaluation_id"),
        sa.UniqueConstraint("run_id"),
    )
    op.create_table(
        "memories",
        sa.Column("memory_id", sa.String(length=36), nullable=False),
        sa.Column("scope", sa.String(length=30), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("tags", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("memory_id"),
    )
    op.create_index(op.f("ix_memories_run_id"), "memories", ["run_id"], unique=False)
    op.create_index(op.f("ix_memories_scope"), "memories", ["scope"], unique=False)
    op.create_index("ix_memories_scope_key", "memories", ["scope", "key"], unique=False)
    op.create_table(
        "product_candidates",
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("market", sa.String(length=100), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("provider_product_id", sa.String(length=200), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("candidate_id"),
    )
    op.create_index(
        op.f("ix_product_candidates_category"), "product_candidates", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_product_candidates_market"), "product_candidates", ["market"], unique=False
    )
    op.create_index(
        op.f("ix_product_candidates_run_id"), "product_candidates", ["run_id"], unique=False
    )
    op.create_table(
        "research_tasks",
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_type", sa.String(length=50), nullable=False),
        sa.Column("assigned_role", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("dependencies", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("task_id"),
    )
    op.create_index(
        op.f("ix_research_tasks_assigned_role"), "research_tasks", ["assigned_role"], unique=False
    )
    op.create_index(op.f("ix_research_tasks_run_id"), "research_tasks", ["run_id"], unique=False)
    op.create_index(op.f("ix_research_tasks_status"), "research_tasks", ["status"], unique=False)
    op.create_index(
        op.f("ix_research_tasks_task_type"), "research_tasks", ["task_type"], unique=False
    )
    op.create_table(
        "risk_flags",
        sa.Column("risk_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.Column("severity", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("evidence_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("risk_id"),
    )
    op.create_index(op.f("ix_risk_flags_run_id"), "risk_flags", ["run_id"], unique=False)
    op.create_table(
        "agent_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("actor", sa.String(length=100), nullable=False),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("parent_event_id", sa.String(length=36), nullable=True),
        sa.Column("input_summary", sa.Text(), nullable=True),
        sa.Column("input_hash", sa.String(length=128), nullable=True),
        sa.Column("output_summary", sa.Text(), nullable=True),
        sa.Column("output_hash", sa.String(length=128), nullable=True),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.task_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("event_id"),
        sa.UniqueConstraint("run_id", "sequence_number", name="uq_agent_events_sequence"),
    )
    op.create_index(
        op.f("ix_agent_events_event_type"), "agent_events", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_agent_events_run_id"), "agent_events", ["run_id"], unique=False)
    op.create_index(op.f("ix_agent_events_timestamp"), "agent_events", ["timestamp"], unique=False)
    op.create_table(
        "benchmark_runs",
        sa.Column("benchmark_run_id", sa.String(length=36), nullable=False),
        sa.Column("suite_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("strategy", sa.String(length=100), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["suite_id"], ["benchmark_suites.suite_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["benchmark_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("benchmark_run_id"),
    )
    op.create_index(
        op.f("ix_benchmark_runs_suite_id"), "benchmark_runs", ["suite_id"], unique=False
    )
    op.create_index(op.f("ix_benchmark_runs_task_id"), "benchmark_runs", ["task_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    op.create_index(op.f("ix_findings_run_id"), "findings", ["run_id"], unique=False)
    op.create_index(op.f("ix_findings_task_id"), "findings", ["task_id"], unique=False)
    op.create_table(
        "product_scores",
        sa.Column("score_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("demand", sa.Float(), nullable=False),
        sa.Column("trend", sa.Float(), nullable=False),
        sa.Column("estimated_margin", sa.Float(), nullable=False),
        sa.Column("competition", sa.Float(), nullable=False),
        sa.Column("customer_pain_opportunity", sa.Float(), nullable=False),
        sa.Column("operational_complexity", sa.Float(), nullable=False),
        sa.Column("regulatory_risk", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["product_candidates.candidate_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("score_id"),
        sa.UniqueConstraint("candidate_id"),
    )
    op.create_index(
        op.f("ix_product_scores_overall_score"), "product_scores", ["overall_score"], unique=False
    )
    op.create_table(
        "tool_calls",
        sa.Column("tool_call_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("input", sa.JSON(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.task_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tool_call_id"),
    )
    op.create_index(op.f("ix_tool_calls_run_id"), "tool_calls", ["run_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    op.create_index(op.f("ix_tool_calls_task_id"), "tool_calls", ["task_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False)
    op.create_table(
        "evidence_items",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("task_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.String(length=36), nullable=False),
        sa.Column("tool_call_id", sa.String(length=36), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=128), nullable=False),
        sa.Column("excerpt", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("related_entity", sa.String(length=200), nullable=True),
        sa.Column("extraction_method", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["research_tasks.task_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.tool_call_id"],
        ),
        sa.PrimaryKeyConstraint("evidence_id"),
    )
    op.create_index(
        op.f("ix_evidence_items_content_hash"), "evidence_items", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_evidence_items_run_id"), "evidence_items", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_evidence_items_source_id"), "evidence_items", ["source_id"], unique=False
    )
    op.create_index(op.f("ix_evidence_items_task_id"), "evidence_items", ["task_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("candidate_id", sa.String(length=36), nullable=False),
        sa.Column("score_id", sa.String(length=36), nullable=False),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["candidate_id"], ["product_candidates.candidate_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["research_runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["score_id"], ["product_scores.score_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("recommendation_id"),
    )
    op.create_index(
        op.f("ix_recommendations_decision"), "recommendations", ["decision"], unique=False
    )
    op.create_index(op.f("ix_recommendations_run_id"), "recommendations", ["run_id"], unique=False)
    op.create_table(
        "finding_evidence",
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_items.evidence_id"],
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.finding_id"],
        ),
        sa.PrimaryKeyConstraint("finding_id", "evidence_id"),
    )
    op.create_table(
        "recommendation_evidence",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id"],
            ["evidence_items.evidence_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.recommendation_id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id", "evidence_id"),
    )
    op.create_table(
        "recommendation_findings",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("finding_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.finding_id"],
        ),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.recommendation_id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id", "finding_id"),
    )
    op.create_table(
        "recommendation_risks",
        sa.Column("recommendation_id", sa.String(length=36), nullable=False),
        sa.Column("risk_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["recommendation_id"],
            ["recommendations.recommendation_id"],
        ),
        sa.ForeignKeyConstraint(
            ["risk_id"],
            ["risk_flags.risk_id"],
        ),
        sa.PrimaryKeyConstraint("recommendation_id", "risk_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("recommendation_risks")
    op.drop_table("recommendation_findings")
    op.drop_table("recommendation_evidence")
    op.drop_table("finding_evidence")
    op.drop_index(op.f("ix_recommendations_run_id"), table_name="recommendations")
    op.drop_index(op.f("ix_recommendations_decision"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_evidence_items_task_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_source_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_run_id"), table_name="evidence_items")
    op.drop_index(op.f("ix_evidence_items_content_hash"), table_name="evidence_items")
    op.drop_table("evidence_items")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_task_id"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_run_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_product_scores_overall_score"), table_name="product_scores")
    op.drop_table("product_scores")
    op.drop_index(op.f("ix_findings_task_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_run_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_benchmark_runs_task_id"), table_name="benchmark_runs")
    op.drop_index(op.f("ix_benchmark_runs_suite_id"), table_name="benchmark_runs")
    op.drop_table("benchmark_runs")
    op.drop_index(op.f("ix_agent_events_timestamp"), table_name="agent_events")
    op.drop_index(op.f("ix_agent_events_run_id"), table_name="agent_events")
    op.drop_index(op.f("ix_agent_events_event_type"), table_name="agent_events")
    op.drop_table("agent_events")
    op.drop_index(op.f("ix_risk_flags_run_id"), table_name="risk_flags")
    op.drop_table("risk_flags")
    op.drop_index(op.f("ix_research_tasks_task_type"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_status"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_run_id"), table_name="research_tasks")
    op.drop_index(op.f("ix_research_tasks_assigned_role"), table_name="research_tasks")
    op.drop_table("research_tasks")
    op.drop_index(op.f("ix_product_candidates_run_id"), table_name="product_candidates")
    op.drop_index(op.f("ix_product_candidates_market"), table_name="product_candidates")
    op.drop_index(op.f("ix_product_candidates_category"), table_name="product_candidates")
    op.drop_table("product_candidates")
    op.drop_index("ix_memories_scope_key", table_name="memories")
    op.drop_index(op.f("ix_memories_scope"), table_name="memories")
    op.drop_index(op.f("ix_memories_run_id"), table_name="memories")
    op.drop_table("memories")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_benchmark_tasks_suite_id"), table_name="benchmark_tasks")
    op.drop_table("benchmark_tasks")
    op.drop_index(op.f("ix_sources_source_type"), table_name="sources")
    op.drop_table("sources")
    op.drop_index(op.f("ix_research_runs_status"), table_name="research_runs")
    op.drop_index("ix_research_runs_market_category", table_name="research_runs")
    op.drop_table("research_runs")
    op.drop_table("experiments")
    op.drop_table("benchmark_suites")
    # ### end Alembic commands ###
